[flyway]
environment = "default"
locations = ["filesystem:./Migrations","filesystem:./Functions","filesystem:./Procedures","filesystem:./Views"]
encoding = 'ISO-8859-1'
reportEnabled = false
sqlMigrationPrefix = 'V'
repeatableSqlMigrationPrefix = 'R'
sqlMigrationSeparator = '__'
sqlMigrationSuffixes = ['.sql']
validateMigrationNaming = true
